#!/bin/bash
ACTIONLOG=actions.log
TMPDIR=/opt/osdp-conformance/tmp
PAYLOAD=${TMPDIR}/response-payload-MFGREP
BINDIR=/opt/tester/bin
LOGDIR=/opt/osdp-conformance/log
LOG=${LOGDIR}/${ACTIONLOG}
mkdir -p ${LOGDIR}
echo >>${LOGDIR}/${ACTIONLOG} osdp_MFGREP called $1 $2 $3 $4 $5 $6 $7 $8
rm -vf ${PAYLOAD}
echo >${PAYLOAD} 2>${LOG} $2
echo >>${LOG} pkoc osdp offload: ${BINDIR}/pkoc-osdp --mfgrep @${PAYLOAD}
echo >>${LOG} pkoc mfgrep payload `cat ${PAYLOAD}`
${BINDIR}/pkoc-osdp --mfgrep @${PAYLOAD} 2>>${LOG}

